name: Build Site

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '*.adoc'
      - '*.txt'
jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build blog
        run: |
          QUARKUS_ROQ_GENERATOR_BATCH=true mvn package quarkus:run -Dsite.future=true -Dsite.draft=true

      - name: Store PR id
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ github.event.number }} >> ./target/roq/pr-id.txt

      - name: Publishing blog
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: ./target/roq
          retention-days: 3